
#General settings
[General]
	#Determines the spoilrate in specific containers [Syntax: tileentity:spoil_rate]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#"cookingforblockheads:fridge,0.2" would make a cooking for blockheads fridge spoil at 20% of the usual spoilrate
	containerModifier = ["minecraft:shulker_box,0", "farmersdelight:basket,0.5", "biomancy:fleshkin_chest,0"]
	#Defines the default total amount of spoiling updates for each food item 
	#(For example, a defaultSpoilTime of 40 means any default food item will have 40 total updates before it spoils. 
	#This can be altered when custom food spoiling is set using a datapack) [default: 30]
	#Range: > 1
	spoilRate = 40
	#When enabled Spoiled initializes spoiling for all vanilla food [default: true]
	initializeSpoiling = true
	#When enabled enables a special recipe to merge spoiling food together [default: false]
	mergeSpoilingFood = true
	#When enabled Spoiled makes every edible item spoil into the specified Spoil Item (This overwrites json spoiling completely) [default: false]
	spoilEverything = true
	#Defines a list of items that are never allowed to spoil
	spoilBlacklist = ["minecraft:rotten_flesh", "minecraft:golden_apple", "minecraft:enchanted_golden_apple", "kubejs:sanity_pile", "kubejs:flower_pie", "kubejs:wood_soup_cup", "kubejs:ration", "born_in_chaos_v1:stimulating_decoction", "born_in_chaos_v1:intoxicating_decoction", "farmersdelight:dog_food", "kubejs:moon_carrot", "kubejs:bun", "kubejs:miner_soup", "kubejs:poor_soup"]
	#Defines the total amount of spoiling updates that is used by the default initialized spoiling when 'initializeSpoiling' is enabled 
	#(If the 'spoilRate' is 10 and the 'defaultSpoilTime' is set to 20 then the food will spoil after 20 * 10 seconds = 200 seconds) [default: 40]
	#Range: > 1
	defaultSpoilTime = 120
	#Defines the item the foods vanilla foods will turn into when spoiled (if empty it will clear the spoiling item) [default: 'minecraft:rotten_flesh']
	defaultSpoilItem = "kubejs:wet_goo"

#Compatibility settings
[Compatibility]
	#When enabled foods that are salted by The Salted mod will not spoil [default: false]
	saltCompat = true
	#Defines a list of nbt tags that stop the item from spoiling
	spoilTagBlacklist = []

